# Generated by Django 4.0.5 on 2023-02-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chesstourney', '0002_tournament_tournament_user_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='full',
            field=models.BooleanField(default=True),
        ),
    ]
