# Generated by Django 4.0.5 on 2023-02-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chesstourney', '0004_alter_tournament_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='slots',
            field=models.IntegerField(default=100),
        ),
    ]
