# Generated by Django 4.0.5 on 2023-02-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chesstourney', '0005_tournament_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='prizes',
            field=models.TextField(default=''),
        ),
    ]
