# Generated by Django 4.0.5 on 2023-02-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chesstourney', '0007_tournament_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(),
        ),
    ]
