# Generated by Django 4.0.5 on 2023-02-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chesstourney', '0009_alter_result_second_alter_result_third_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament_user',
            name='total_score',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
